(function(){
'use strict';
const host=document.getElementById('viewEQ'),types={peaking:'Campana (PEQ)',highpass:'Pasa altos (HPF)',lowpass:'Pasa bajos (LPF)',lowshelf:'Shelf de graves',highshelf:'Shelf de agudos',notch:'Rechazo (notch)'},colors=['#e7b756','#79c9b1','#87b8ec','#d79add','#ec9276','#c6d775'];
let bands=[],selected=0,bypass=false,drag=null;
const makeBand=(frequency=1000,gain=0,type='peaking')=>({frequency,gain,type,q:.707,enabled:true});
host.innerHTML=`<div class="eq-visual"><p class="eyebrow">Explora la curva · sin procesar audio</p><h2>Ecualizador visual</h2><p>Arrastra una banda: izquierda/derecha cambia la frecuencia; arriba/abajo cambia la ganancia de una campana o shelf. También puedes escribir los valores y ajustar Q con el control.</p><p id="eqContext" class="eq-status" role="status">Empieza con una curva plana o abre un ejemplo desde la ficha de un instrumento.</p><div class="eq-toolbar"><button id="eqAdd">Añadir banda</button><button id="eqReset">Restablecer</button><button id="eqBypass" aria-pressed="false">Comparar con curva plana</button></div><div id="eqBands" class="eq-bands" aria-label="Seleccionar banda"></div><svg id="eqGraph" class="eq-graph" viewBox="0 0 960 360" role="img" aria-label="Respuesta del ecualizador, frecuencia de 20 Hz a 20 kHz y ganancia de menos 24 a más 18 decibelios"></svg><div class="eq-controls"><label>Tipo de filtro<select id="eqType">${Object.entries(types).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><label>Frecuencia (Hz)<input id="eqFrequency" type="number" min="20" max="20000" step="1"><input id="eqFrequencyRange" aria-label="Frecuencia de la banda" type="range" min="0" max="1000" step="1"></label><label>Ganancia (dB)<input id="eqGain" type="number" min="-18" max="18" step="0.1"><input id="eqGainRange" aria-label="Ganancia de la banda" type="range" min="-18" max="18" step="0.1"></label><label>Factor Q<input id="eqQ" type="number" min="0.2" max="12" step="0.01"><input id="eqQRange" aria-label="Q de la banda" type="range" min="0.2" max="12" step="0.01"></label></div><div class="eq-toolbar"><button id="eqEnabled" aria-pressed="true">Banda activa</button><button id="eqRemove">Eliminar banda</button></div><p id="eqExplanation"></p><p>La curva dorada suma las bandas activas; la curva de color muestra la banda seleccionada. Q alto estrecha una campana o notch; en HPF/LPF controla la resonancia. Estos cortes son de 12 dB/octava y los shelves usan pendiente fija sin resonancia. El gráfico se recorta entre −24 y +18 dB.</p><details><summary>Cómo practicar</summary><p>1. Identifica qué sobra o falta. 2. Elige campana para una zona, shelf para un extremo o HPF/LPF para limitar graves/agudos. 3. Cambia frecuencia, ganancia y Q y observa la curva. 4. Compara con la curva plana. Una curva por sí sola no permite juzgar el sonido: contrástala después con la grabación.</p><p>Los ejemplos usan ±3 dB y Q 1 como valores didácticos editables, no como ajustes obligatorios. Las zonas de de-esser se representan como cortes estáticos: el de-esser real actúa dinámicamente.</p><a href="https://www.w3.org/TR/audio-eq-cookbook/" target="_blank" rel="noopener noreferrer">Modelo de respuesta: Audio EQ Cookbook</a></details></div>`;
const $=id=>document.getElementById(id),svg=$('eqGraph'),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),x=f=>56+Math.log10(f/20)/3*880,y=d=>24+(18-clamp(d,-24,18))/42*300,hz=p=>20*1000**clamp((p-56)/880,0,1),db=p=>clamp(18-(p-24)/300*42,-18,18),gainType=b=>['peaking','lowshelf','highshelf'].includes(b.type);
function draw(){
 let out='';for(const d of [-24,-18,-12,-6,0,6,12,18])out+=`<path d="M56 ${y(d)}H936" stroke="${d===0?'#8c8b7c':'#34372f'}"/><text x="48" y="${y(d)+4}" text-anchor="end" fill="#d0c9bb" font-size="13">${d}</text>`;
 for(const f of [20,50,100,200,500,1000,2000,5000,10000,20000])out+=`<path d="M${x(f)} 24V324" stroke="#34372f"/><text x="${x(f)}" y="348" text-anchor="middle" fill="#d0c9bb" font-size="13">${f>=1000?f/1000+'k':f}</text>`;
 const path=fn=>Array.from({length:500},(_,i)=>{const f=20*1000**(i/499);return `${i?'L':'M'}${x(f).toFixed(2)} ${y(fn(f)).toFixed(2)}`;}).join(' ');
 out+=`<path d="${path(f=>bypass?0:EQResponse.response(bands[selected],f))}" fill="none" stroke="${colors[selected%colors.length]}" stroke-width="1.5" stroke-dasharray="5 4"/><path d="${path(f=>bypass?0:bands.reduce((sum,b)=>sum+EQResponse.response(b,f),0))}" fill="none" stroke="#edbf58" stroke-width="3"/>`;
 bands.forEach((b,i)=>out+=`<circle data-band="${i}" cx="${x(b.frequency)}" cy="${y(gainType(b)?b.gain:0)}" r="${i===selected?10:7}" fill="${b.enabled?colors[i%colors.length]:'#666'}" stroke="#fff" stroke-width="${i===selected?2:0}"/><text x="${x(b.frequency)}" y="${y(gainType(b)?b.gain:0)-16}" text-anchor="middle" fill="${colors[i%colors.length]}" font-size="14">${i+1}</text>`);svg.innerHTML=out;
}
function sync(){
 const b=bands[selected],gain=gainType(b),shelf=b.type.includes('shelf');
 $('eqBands').innerHTML=bands.map((v,i)=>`<button data-select="${i}" aria-pressed="${i===selected}">Banda ${i+1}${v.enabled?'':' · apagada'}</button>`).join('');
 $('eqType').value=b.type;$('eqFrequency').value=Math.round(b.frequency);$('eqFrequencyRange').value=Math.log10(b.frequency/20)/3*1000;
 for(const id of ['eqGain','eqGainRange']){$(id).value=b.gain.toFixed(1);$(id).disabled=!gain;}
 for(const id of ['eqQ','eqQRange']){$(id).value=b.q.toFixed(2);$(id).disabled=shelf;}
 $('eqEnabled').setAttribute('aria-pressed',b.enabled);$('eqEnabled').textContent=b.enabled?'Banda activa':'Banda apagada';$('eqBypass').setAttribute('aria-pressed',bypass);$('eqAdd').disabled=bands.length>=12;$('eqRemove').disabled=bands.length===1;
 $('eqExplanation').textContent=`Banda ${selected+1}: ${types[b.type]}, ${Math.round(b.frequency)} Hz. `+(gain?`${b.gain>0?'Realce':'Atenuación'} de ${Math.abs(b.gain).toFixed(1)} dB. `:'No usa ganancia: cambia la frecuencia de corte o rechazo. ')+(shelf?'Pendiente fija.':`Q ${b.q.toFixed(2)}.`)+(b.label?' '+b.label:'')+(bypass?' Comparación plana activa.':'');draw();
}
function reset(){bands=[makeBand(100),makeBand(1000),makeBand(8000)];selected=1;bypass=false;$('eqContext').textContent='Curva plana. Selecciona una banda y modifica sus controles.';sync();}
$('eqBands').onclick=e=>{const b=e.target.closest('[data-select]');if(b){selected=+b.dataset.select;sync();}};
$('eqType').onchange=e=>{bands[selected].type=e.target.value;sync();};
for(const [id,key,min,max] of [['eqFrequency','frequency',20,20000],['eqGain','gain',-18,18],['eqGainRange','gain',-18,18],['eqQ','q',.2,12],['eqQRange','q',.2,12]])$(id).addEventListener('input',e=>{const raw=e.target.value;if(raw!==''&&Number.isFinite(+raw)){bands[selected][key]=clamp(+raw,min,max);sync();if(!id.includes('Range'))e.target.value=raw;}});
$('eqFrequencyRange').oninput=e=>{bands[selected].frequency=20*1000**(+e.target.value/1000);sync();};
$('eqAdd').onclick=()=>{if(bands.length<12){bands.push(makeBand());selected=bands.length-1;sync();}};$('eqReset').onclick=reset;$('eqRemove').onclick=()=>{if(bands.length>1){bands.splice(selected,1);selected=Math.min(selected,bands.length-1);sync();}};$('eqEnabled').onclick=()=>{bands[selected].enabled=!bands[selected].enabled;sync();};$('eqBypass').onclick=()=>{bypass=!bypass;sync();};
svg.onpointerdown=e=>{const node=e.target.closest('[data-band]');if(!node)return;selected=+node.dataset.band;drag=e.pointerId;svg.setPointerCapture(drag);sync();};
svg.onpointermove=e=>{if(drag!==e.pointerId)return;const r=svg.getBoundingClientRect(),b=bands[selected];b.frequency=hz((e.clientX-r.left)/r.width*960);if(gainType(b))b.gain=db((e.clientY-r.top)/r.height*360);sync();};
svg.onpointerup=svg.onpointercancel=()=>{drag=null;};
document.addEventListener('click',e=>{const btn=e.target.closest('.eq-example-btn');if(!btn)return;const example=JSON.parse(btn.dataset.example);bands=example.bands;selected=0;bypass=false;$('eqContext').textContent=`Ejemplo completo: ${btn.dataset.context} · ${bands.length} bandas. Cortes y realces reunidos para explorar, no una receta que debas aplicar completa. Ganancia y Q ilustrativos.${example.unspecified.length?" Sin frecuencia definida (no se dibuja): "+example.unspecified.join("; "):""}`;document.querySelector('[data-view="eq"]').click();document.getElementById('detailClose').click();sync();host.scrollIntoView({behavior:'smooth',block:'start'});});
reset();
})();
