/* Original educational arrangements; values describe a visual model, not measured audio. */
(function () {
  const track=(name,pan,register,width,depth,level,color)=>({name,pan,register,width,depth,level,color});
  const gold='#e4b951', blue='#69b8e5', green='#80c6a2', purple='#bf99df';
  const presets={
    pop:{title:'Pop',note:'Voz protagonista al centro; guitarras de tomas distintas a los lados y coros detrás. Comprueba también el balance en mono.',tracks:[track('Voz',0,56,8,10,90,gold),track('Bajo',0,16,5,18,75,blue),track('Bombo',0,6,5,5,85,green),track('Caja',0,38,8,22,70,green),track('Guitarra L',-65,48,12,35,60,purple),track('Guitarra R',65,48,12,35,60,purple),track('Coros',0,73,75,75,45,gold),track('Platos',20,92,65,55,40,green)]},
    rock:{title:'Rock',note:'Guitarras dobles abiertas, con bombo, bajo, caja y voz como eje central. Abrir dos tomas distintas no equivale a duplicar una pista mono.',tracks:[track('Voz',0,65,6,8,85,gold),track('Guitarra L',-80,48,10,20,85,purple),track('Guitarra R',80,48,10,20,85,purple),track('Bajo',0,18,4,15,80,blue),track('Bombo',0,6,4,10,85,green),track('Caja',0,38,6,15,80,green),track('Overheads',0,88,90,60,55,green)]},
    jazz:{title:'Jazz acústico',note:'Un posible cuarteto: conserva espacio entre solista, piano, contrabajo y batería. La perspectiva y la sala pueden cambiar estas posiciones.',tracks:[track('Saxo',-18,60,8,12,80,gold),track('Piano',45,46,40,30,65,purple),track('Contrabajo',-20,15,6,25,65,blue),track('Bombo',15,6,8,45,40,green),track('Caja / escobillas',20,70,15,45,45,green),track('Ride',55,92,20,50,50,green)]},
    folk:{title:'Folk / acústico',note:'La voz y el instrumento principal llevan el relato. Un acompañamiento lateral y una sala discreta dejan espacio sin exigir una mezcla simétrica.',tracks:[track('Voz',0,62,6,8,90,gold),track('Guitarra',-35,40,20,22,70,purple),track('Requinto',45,78,10,30,55,purple),track('Contrabajo',0,12,5,30,55,blue),track('Shaker',55,94,8,50,30,green)]},
    latin:{title:'Pop latino',note:'Voz, bajo y bombo al centro; distribuye percusión y acompañamiento según el arreglo. Evita que varias capas ocupen siempre el mismo espacio.',tracks:[track('Voz',0,62,6,10,90,gold),track('Bajo',0,16,5,15,80,blue),track('Bombo',0,5,5,10,75,green),track('Congas',-40,40,20,35,55,green),track('Bongós',40,75,15,30,55,green),track('Shaker',65,94,8,50,35,green),track('Piano',-55,60,25,40,60,purple),track('Metales',30,48,40,45,65,gold)]},
    electronic:{title:'Electrónica',note:'Base grave centrada como punto de partida; pads y efectos más abiertos. El ancho aparente no garantiza compatibilidad mono: compruébala escuchando.',tracks:[track('Lead',0,62,20,15,85,gold),track('Subgrave',0,5,4,10,80,blue),track('Bombo',0,18,5,5,90,green),track('Clap',0,42,20,25,60,green),track('Hi-hats',35,94,40,30,45,green),track('Pad',0,78,90,85,45,purple),track('Efectos',-55,52,35,80,35,purple)]}
  };
  if(typeof module!=='undefined'&&module.exports)module.exports=presets;
  if(typeof document==='undefined')return;
  const root=document.getElementById('mixMap'); if(!root)return;
  root.innerHTML=`<header><p class="detail-eyebrow">Escena estéreo · referencia visual</p><h2>Mapa de mezcla</h2><p>Explora dónde situar cada sonido. Selecciona un instrumento en el gráfico o en la lista.</p></header><div class="mix-toolbar"><label>Estilo <select id="mixStyle">${Object.entries(presets).map(([k,p])=>`<option value="${k}">${p.title}</option>`).join('')}</select></label><button id="mixReset" type="button">Restablecer estilo</button></div><p id="mixNote"></p><div class="mix-layout"><div class="mix-stage"><svg id="mixSvg" viewBox="0 0 800 540" role="group" aria-label="Mapa de paneo y registro"></svg><p>Izquierda ↔ derecha: paneo · Arriba: agudos · Abajo: graves</p></div><div class="mix-controls"><label>Instrumento <select id="mixTrack"></select></label>${[['pan','Paneo',-100,100],['register','Registro visual',0,100],['width','Amplitud estéreo',0,100],['depth','Profundidad',0,100],['level','Protagonismo',0,100]].map(([id,label,min,max])=>`<label for="mix-${id}">${label} <output id="mix-out-${id}"></output></label><input id="mix-${id}" type="range" min="${min}" max="${max}" step="1">`).join('')}<p>Más profundidad: halo mayor y sonido más tenue. Más protagonismo: núcleo mayor. El ancho representa la extensión de una fuente estéreo.</p></div></div><details><summary>Cómo interpretar el mapa</summary><p>Es un esquema del arreglo, no un analizador de frecuencias ni un procesador de audio. El registro resume la zona relativa de cada sonido; los instrumentos tienen fundamentales, armónicos y ataques que se solapan. Los números de los controles son unidades visuales, no Hz, dB ni tiempos de reverberación.</p><p>La profundidad puede sugerirse con nivel, reverberación, predelay y balance espectral; no depende de un solo control. Los estilos son propuestas editables, no reglas ni mediciones de canciones. Escucha el arreglo, revisa el centro y compara en mono antes de decidir.</p><p>Concepto de espacio visual inspirado en David Gibson, <em>The Art of Mixing</em>, 4.ª edición, capítulos 2, 3 y 6. Gráficos y arreglos originales de Crescendo.</p></details>`;
  const $=id=>document.getElementById(id); let tracks=[],selected=0;
  function describe(key,value){return key==='pan'?(value===0?'Centro':`${Math.abs(value)} ${value<0?'L':'R'}`):`${value} / 100`;}
  function controls(){const t=tracks[selected];$('mixTrack').value=String(selected);for(const k of ['pan','register','width','depth','level']){$('mix-'+k).value=t[k];$('mix-out-'+k).textContent=describe(k,t[k]);$('mix-'+k).setAttribute('aria-valuetext',describe(k,t[k]));}}
  function draw(){
    const grid=[0,25,50,75,100].map(n=>`<path d="M70 ${465-n*3.8}H730" stroke="#ffffff15"/><path d="M${70+n*6.6} 85V465" stroke="#ffffff15"/>`).join('');
    $('mixSvg').innerHTML=`<defs><linearGradient id="mixBg" x2="0" y2="1"><stop stop-color="#293741"/><stop offset="1" stop-color="#181817"/></linearGradient></defs><rect x="1" y="1" width="798" height="538" rx="18" fill="url(#mixBg)" stroke="#ffffff25"/>${grid}<path d="M400 55V480" stroke="#d6af5260" stroke-dasharray="5 7"/><g fill="#e7e1d4" font-size="16" text-anchor="middle"><text x="85" y="35">L</text><text x="400" y="35">Centro</text><text x="715" y="35">R</text><text x="400" y="68">Agudos / brillo</text><text x="400" y="517">Graves / fundamento</text></g>`+tracks.map((t,i)=>{
      const rx=30+t.level*.18+t.width*1.15,ry=14+t.level*.12,x=rx+18+(t.pan+100)/200*(800-2*(rx+18)),y=465-t.register*3.8;
      return `<g role="button" tabindex="0" data-track="${i}" aria-label="${t.name}, ${describe('pan',t.pan)}" aria-pressed="${i===selected}" style="cursor:pointer"><ellipse cx="${x}" cy="${y}" rx="${rx+6}" ry="${ry+8+t.depth*.12}" fill="${t.color}" opacity="${.06+t.depth*.002}"/><ellipse cx="${x}" cy="${y}" rx="${rx}" ry="${ry}" fill="${t.color}" fill-opacity="${.8-t.depth*.004}" stroke="${i===selected?'#fff':t.color}" stroke-width="${i===selected?3:1}"/><text x="${x}" y="${y+5}" text-anchor="middle" fill="#fff" font-size="16" font-weight="600" stroke="#151515" stroke-width="3" paint-order="stroke">${t.name}</text></g>`;
    }).join('');
  }
  function load(){const p=presets[$('mixStyle').value];tracks=p.tracks.map(t=>({...t}));selected=0;$('mixNote').textContent=p.note;$('mixTrack').innerHTML=tracks.map((t,i)=>`<option value="${i}">${t.name}</option>`).join('');controls();draw();}
  $('mixStyle').addEventListener('change',load);$('mixReset').addEventListener('click',load);
  $('mixTrack').addEventListener('change',()=>{selected=Number($('mixTrack').value);controls();draw();});
  for(const k of ['pan','register','width','depth','level'])$('mix-'+k).addEventListener('input',()=>{tracks[selected][k]=Number($('mix-'+k).value);controls();draw();});
  function select(e){const g=e.target.closest('[data-track]');if(!g)return;selected=Number(g.dataset.track);controls();draw();return selected;}
  $('mixSvg').addEventListener('click',select);$('mixSvg').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();const i=select(e);if(i!==undefined)$('mixSvg').querySelector(`[data-track="${i}"]`).focus();}});
  load();
})();
