/* Original educational scenes. No audio processing or measured spectra. */
(function(){
'use strict';
const C=window.MixCatalog,root=document.getElementById('mixMap');if(!C||!root)return;
const presets={...C.presets},KEY='crescendo-mix-scenes-v1',esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const keys=['pan','register','width','depth','level'];let saved={},tracks=[],selected=0,current='pop',verticalAxis='depth';
function validTrack(t){return t&&typeof t.name==='string'&&t.name.length>0&&t.name.length<=40&&/^#[0-9a-f]{6}$/i.test(t.color)&&keys.every(k=>Number.isFinite(t[k])&&t[k]>=(k==='pan'?-100:0)&&t[k]<=100);}
try{const value=JSON.parse(localStorage.getItem(KEY)||'{}');if(value&&typeof value==='object'&&!Array.isArray(value))for(const [id,p] of Object.entries(value).slice(0,40)){if(/^custom-[a-z0-9-]+$/.test(id)&&typeof p.title==='string'&&p.title.length<=60&&Array.isArray(p.tracks)&&p.tracks.length>0&&p.tracks.length<=20&&p.tracks.every(validTrack)){saved[id]={title:p.title,tracks:p.tracks.map(t=>({...t})),family:'custom',basis:'custom',sources:[],note:'Tu mapa personalizado. Ajusta el arreglo y guarda para conservar los cambios.'};presets[id]=saved[id];}}}catch(_){}
const families={...C.families,custom:'Mis mapas'};
root.innerHTML=`<header><p class="detail-eyebrow">Escena estéreo · referencia visual</p><h2>Mapa de mezcla</h2><p>Explora ${Object.keys(C.presets).length} escenarios por familias. Son puntos de partida editables; las tradiciones, fusiones y subgéneros no forman una lista cerrada.</p></header>
<div class="mix-toolbar mix-catalog"><label>Buscar estilo<input id="mixSearch" type="search" placeholder="Busca en todo el catálogo…"></label><label>Familia<select id="mixFamily"><option value="all">Todas las familias</option>${Object.entries(families).map(([id,name])=>`<option value="${id}">${esc(name)}</option>`).join('')}</select></label><label>Estilo<select id="mixStyle"></select></label><div class="mix-axis-field"><span id="mixAxisLabel">Eje vertical</span><div id="mixAxis" class="mix-axis-pill" role="group" aria-labelledby="mixAxisLabel"><button type="button" data-axis="depth" aria-pressed="true">Profundidad</button><button type="button" data-axis="register" aria-pressed="false">Registro</button></div></div><button id="mixReset" type="button">Restablecer estilo</button></div><div class="mix-quick" aria-label="Accesos rápidos"><button type="button" data-mix-quick="reggaeton">Reguetón</button><button type="button" data-mix-quick="afrobeats">Afrobeats</button><button type="button" data-mix-quick="indie-pop">Indie</button><button type="button" data-mix-quick="city-pop">City pop</button><button type="button" data-mix-quick="k-pop">K-pop</button><button type="button" data-mix-quick="ambient-chill">Ambient chill</button><button type="button" data-mix-quick="edm">EDM</button><button type="button" id="mixClear">Ver todos</button></div><p id="mixCount" role="status"></p>
<h3 id="mixTitle"></h3><p id="mixNote"></p><div class="mix-layout"><div class="mix-stage"><svg id="mixSvg" viewBox="0 0 800 570" role="group" aria-label="Mapa de paneo y profundidad"></svg><p id="mixLegend"></p></div><div class="mix-controls"><label>Instrumento<select id="mixTrack"></select></label>${[['pan','Paneo',-100],['register','Registro visual',0],['width','Amplitud estéreo',0],['depth','Profundidad',0],['level','Protagonismo',0]].map(([id,label,min])=>`<label for="mix-${id}">${label}<output id="mix-out-${id}"></output></label><input id="mix-${id}" type="range" min="${min}" max="100" step="1">`).join('')}<p>Más protagonismo: figura mayor. Profundidad 0: primer plano; 100: fondo. El registro se ve al cambiar el eje vertical.</p></div>
<details id="mixEditor"><summary>Personalizar instrumentos y guardar un estilo</summary><p>Parte del mapa actual y adapta la instrumentación para cualquier género, subgénero o fusión. Los cambios de estilo descartan ajustes que no hayas guardado.</p><div class="mix-toolbar"><label>Nombre del instrumento<input id="mixName" maxlength="40"></label><button id="mixRename" type="button">Renombrar</button><button id="mixAdd" type="button">Añadir instrumento</button><button id="mixRemove" type="button">Quitar seleccionado</button></div><div class="mix-toolbar"><label>Nombre de tu mapa<input id="mixCustomTitle" maxlength="60" placeholder="Ej. Mi fusión de jazz y pasillo"></label><button id="mixSave" type="button">Guardar en este navegador</button><button id="mixDelete" type="button" disabled>Eliminar mapa guardado</button><button id="mixExport" type="button">Descargar mapa JSON</button></div><p id="mixStatus" role="status"></p></details>
<details id="mixHelp"><summary>Cómo interpretar el mapa y fuentes</summary><p>El eje horizontal representa paneo. En la vista Profundidad, arriba es fondo y abajo primer plano; en la vista Registro, arriba es agudo y abajo grave. Tamaño representa protagonismo; extensión horizontal, amplitud. Los valores son unidades visuales, no Hz, dB ni tiempos de reverb.</p><p>La profundidad percibida depende de nivel, reverberación, predelay, timbre y captación. Este esquema no procesa audio ni mide una canción. Los sonidos ocupan varios registros; las posiciones y la instrumentación son ejemplos, no una receta universal. Revisa la mezcla en mono y respeta la imagen de los micrófonos principales en conjuntos acústicos.</p><p id="mixBasis"></p><ul id="mixSources"></ul><p>Los nombres de las pistas usan inglés; instrumentos tradicionales como requinto o charango conservan su nombre habitual. Las líneas unen las etiquetas desplazadas a sus figuras y no representan señales de audio. Seleccionar no cambia posiciones. Gráficos y arreglos originales de Crescendo. Inspiración visual: David Gibson, <em>The Art of Mixing</em>, 4.ª edición, visuales A–M y capítulos 2, 3 y 6. Las fuentes profesionales explican principios; no avalan las coordenadas de cada propuesta.</p></details></div>`;
const $=id=>document.getElementById(id),fold=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function filter(){const family=$('mixFamily').value,q=$('mixSearch').value.trim();const entries=C.search(presets,q,family);$('mixStyle').replaceChildren();for(const [id,p] of entries){const o=document.createElement('option');o.value=id;o.textContent=p.title;$('mixStyle').append(o);}$('mixStyle').disabled=!entries.length;$('mixCount').textContent=entries.length?`${entries.length} estilos encontrados. Selecciona uno para cargarlo.`:'Sin coincidencias. El mapa actual se conserva; cambia la búsqueda o crea uno personalizado.';if(entries.some(([id])=>id===current))$('mixStyle').value=current;else $('mixStyle').selectedIndex=-1;}
function describe(k,v){return k==='pan'?(v===0?'Centro':`${Math.abs(v)} ${v<0?'L':'R'}`):k==='depth'?(v===0?'0 · Primer plano':v===100?'100 · Fondo':`${v} / 100`):`${v} / 100`;}
function controls(){const t=tracks[selected];$('mixTrack').value=String(selected);$('mixName').value=t.name;for(const k of keys){$('mix-'+k).value=t[k];$('mix-out-'+k).textContent=describe(k,t[k]);$('mix-'+k).setAttribute('aria-valuetext',describe(k,t[k]));}$('mixRemove').disabled=tracks.length===1;$('mixAdd').disabled=tracks.length>=20;}
function trackList(){ $('mixTrack').innerHTML=tracks.map((t,i)=>`<option value="${i}">${esc(t.name)}</option>`).join('');controls();}
function draw(){const depth=verticalAxis==='depth',axis=depth?'depth':'register',top=depth?'FONDO · 100':'AGUDOS',bottom=depth?'PRIMER PLANO · 0':'GRAVES';
$('mixSvg').setAttribute('aria-label',depth?'Mapa de paneo y profundidad':'Mapa de paneo y registro');$('mixLegend').textContent=depth?'Horizontal: L ↔ R · Vertical: primer plano ↕ fondo. Selecciona una figura o usa la lista.':'Horizontal: L ↔ R · Vertical: graves ↕ agudos. La profundidad permanece editable en su control.';
let content=`<defs><linearGradient id="mixBg" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#18272e"/><stop offset="1" stop-color="#40392a"/></linearGradient></defs><rect x="1" y="1" width="798" height="568" rx="18" fill="url(#mixBg)" stroke="#ffffff25"/>`;
for(const n of [0,25,50,75,100]){const y=475-n*3.7;content+=`<path d="M100 ${y}H740" stroke="#ffffff18"/><path d="M${100+n*6.4} 105V475" stroke="#ffffff12"/>`;if(depth)content+=`<text x="62" y="${y+5}" fill="#d2cfc5" text-anchor="end" font-size="14">${n}</text>`;}
content+=`<path d="M80 105V475M75 115L80 105L85 115M75 465L80 475L85 465" stroke="#e4b951" fill="none"/><path d="M420 90V490" stroke="#d6af5260" stroke-dasharray="5 7"/><g fill="#f3ead6" font-size="17" text-anchor="middle"><text x="130" y="34">L</text><text x="420" y="34">Centro</text><text x="710" y="34">R</text><text x="420" y="76">${top}</text><text x="420" y="535">${bottom}</text><text transform="translate(25 295) rotate(-90)">${depth?'PROFUNDIDAD':'REGISTRO'}</text></g>`;
// Geometry and label allocation use catalog order, never selection order.
const labelBoxes=[];
function labelPosition(x,y,text){const w=Math.min(184,text.length*8+12);for(const dx of [0,-100,100,-200,200])for(const dy of [0,-28,28,-56,56,-84,84,-112,112,-140,140]){const cx=Math.max(100+w/2,Math.min(740-w/2,x+dx)),cy=Math.max(110,Math.min(480,y+dy)),box={x:cx-w/2,y:cy-11,w,h:22};if(!labelBoxes.some(b=>box.x<b.x+b.w+4&&box.x+box.w+4>b.x&&box.y<b.y+b.h+3&&box.y+box.h+3>b.y)){labelBoxes.push(box);return {x:cx,y:cy,w};}}return {x,y,w};}
const positions=tracks.map(t=>{const rx=23+t.level*.16+t.width*.92;return {rx,ry:12+t.level*.1,x:100+rx+(t.pan+100)/200*(640-2*rx),y:475-t[axis]*3.7,label:t.name.length>22?t.name.slice(0,21)+'…':t.name};});
const labels=[];tracks.map((_,i)=>i).forEach(i=>{const p=positions[i];labels[i]=labelPosition(p.x,p.y,p.label);});
const order=tracks.map((t,i)=>({t,i}));
let labelLayer='';
for(const {t,i} of order){const {rx,ry,x,y,label}=positions[i],lp=labels[i];
content+=`<g role="button" tabindex="0" data-track="${i}" aria-label="${esc(t.name)}, ${describe('pan',t.pan)}, profundidad ${t.depth}" aria-pressed="${i===selected}" style="cursor:pointer"><title>${esc(t.name)} · ${describe('pan',t.pan)} · profundidad ${t.depth}</title><ellipse cx="${x}" cy="${y}" rx="${rx+5}" ry="${ry+6+t.depth*.09}" fill="${t.color}" opacity="${.07+t.depth*.002}"/><ellipse cx="${x}" cy="${y}" rx="${rx}" ry="${ry}" fill="${t.color}" fill-opacity="${.83-t.depth*.004}" stroke="${i===selected?'#fff':t.color}" stroke-width="${i===selected?3:1}"/></g>`;
labelLayer+=`<g data-track="${i}" aria-hidden="true" style="cursor:pointer"><path d="M${x} ${y}L${lp.x} ${lp.y}" stroke="${t.color}" stroke-width="1.5"/><rect x="${lp.x-lp.w/2}" y="${lp.y-11}" width="${lp.w}" height="22" rx="5" fill="#151b20" fill-opacity=".9"/><text x="${lp.x}" y="${lp.y+5}" text-anchor="middle" fill="#fff" font-size="15" font-weight="600" stroke="#151515" stroke-width="3" paint-order="stroke">${esc(label)}</text></g>`;}
$('mixSvg').innerHTML=content+labelLayer;}
function load(id=current){if(!presets[id])return;current=id;const p=presets[id];tracks=p.tracks.map(t=>({...t}));selected=0;$('mixDelete').disabled=p.family!=='custom';$('mixTitle').textContent=p.title;$('mixNote').textContent=p.note;$('mixCustomTitle').value=p.family==='custom'?p.title:'';$('mixBasis').textContent=p.basis==='book'?'Estilo presente en los visuales A–M del libro. Este mapa es una interpretación original; no reproduce una canción ni sus coordenadas.':p.basis==='custom'?'Mapa personalizado por ti.':'Propuesta original de arreglo y mezcla. No se presenta como una norma de este género ni como una medición.';$('mixSources').innerHTML=(p.sources||[]).map(id=>{const s=C.sources[id];return `<li><a href="${s.url}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a></li>`;}).join('');$('mixStatus').textContent='';trackList();draw();}
$('mixSearch').addEventListener('input',()=>{if($('mixSearch').value.trim())$('mixFamily').value='all';filter();});$('mixFamily').addEventListener('change',filter);$('mixStyle').addEventListener('change',()=>load($('mixStyle').value));$('mixReset').addEventListener('click',()=>load());$('mixAxis').addEventListener('click',e=>{const b=e.target.closest('[data-axis]');if(!b)return;verticalAxis=b.dataset.axis;$('mixAxis').querySelectorAll('button').forEach(t=>t.setAttribute('aria-pressed',String(t===b)));draw();});
$('mixAxis').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const index=e.key==='Home'?0:e.key==='End'?1:verticalAxis==='depth'?1:0;const b=$('mixAxis').querySelectorAll('button')[index];b.click();b.focus();});
$('mixClear').addEventListener('click',()=>{$('mixSearch').value='';$('mixFamily').value='all';filter();});
root.querySelectorAll('[data-mix-quick]').forEach(b=>b.addEventListener('click',()=>{$('mixSearch').value='';$('mixFamily').value='all';current=b.dataset.mixQuick;filter();load(current);}));
$('mixTrack').addEventListener('change',()=>{selected=Number($('mixTrack').value);controls();draw();});for(const k of keys)$('mix-'+k).addEventListener('input',()=>{tracks[selected][k]=Number($('mix-'+k).value);controls();draw();});
function select(e){const g=e.target.closest('[data-track]');if(!g)return;selected=Number(g.dataset.track);controls();draw();return selected;}
$('mixSvg').addEventListener('click',select);$('mixSvg').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();const i=select(e);if(i!==undefined)$('mixSvg').querySelector(`[role="button"][data-track="${i}"]`).focus();}});
$('mixRename').addEventListener('click',()=>{const name=$('mixName').value.trim();if(!name){$('mixStatus').textContent='Escribe un nombre de instrumento.';return;}tracks[selected].name=name.slice(0,40);trackList();draw();});
$('mixAdd').addEventListener('click',()=>{if(tracks.length>=20)return;tracks.push({name:'New instrument',pan:0,register:50,width:15,depth:45,level:65,color:'#bf99df'});selected=tracks.length-1;trackList();draw();$('mixName').focus();});
$('mixRemove').addEventListener('click',()=>{if(tracks.length<=1)return;tracks.splice(selected,1);selected=Math.min(selected,tracks.length-1);trackList();draw();});
function snapshot(){return {title:$('mixCustomTitle').value.trim().slice(0,60)||presets[current].title,tracks:tracks.map(t=>({...t})),family:'custom',basis:'custom',sources:[],note:'Tu mapa personalizado. Ajusta el arreglo y guarda para conservar los cambios.'};}
$('mixSave').addEventListener('click',()=>{if(!$('mixCustomTitle').value.trim()){$('mixStatus').textContent='Escribe un nombre para tu mapa.';return;}const p=snapshot();const existing=Object.keys(saved).find(k=>fold(saved[k].title)===fold(p.title));if(!existing&&Object.keys(saved).length>=40){$('mixStatus').textContent='Tienes 40 mapas guardados. Usa un nombre existente para actualizarlo o descarga este mapa.';return;}const id=existing||'custom-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);const next={...saved,[id]:p};try{localStorage.setItem(KEY,JSON.stringify(next));saved=next;presets[id]=p;current=id;$('mixFamily').value='custom';$('mixSearch').value='';filter();load(id);$('mixStatus').textContent='Mapa guardado en este navegador. El mismo nombre actualiza su mapa guardado.';}catch(_){$('mixStatus').textContent='El navegador no permite guardar. Puedes descargar el mapa JSON.';}});
$('mixDelete').addEventListener('click',()=>{if(!saved[current])return;const next={...saved};delete next[current];try{localStorage.setItem(KEY,JSON.stringify(next));delete presets[current];saved=next;current='pop';$('mixFamily').value='all';$('mixSearch').value='';filter();load();$('mixStatus').textContent='Mapa personalizado eliminado.';}catch(_){$('mixStatus').textContent='No se pudo eliminar el mapa guardado.';}});
$('mixExport').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,...snapshot()},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='crescendo-mapa-mezcla.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('mixStatus').textContent='Descarga solicitada: crescendo-mapa-mezcla.json.';});
filter();load();
})();
