(function(){
'use strict';
const D=window.ProcessingDSP,$=id=>document.getElementById(id),sr=32000;
const lessons={
 eq:['EQ estática','Una banda cambia el balance tonal durante todo el fragmento. Frecuencia elige la zona; ganancia decide realce o recorte; Q alto concentra el cambio. Escucha en contexto y compara a volumen similar.'],
 filter:['Filtros y pendiente','El pasa-altos atenúa progresivamente por debajo de la frecuencia elegida. La pendiente se expresa en dB por octava: no es una pared. Sube el corte hasta reconocer cuándo desaparecen el retumbo y después el cuerpo musical.'],
 dynamic:['EQ dinámica','Aquí una banda se atenúa cuando su nivel supera el umbral. Compárala con EQ estática: actúa solo cuando la energía lo exige. El detector de este ejemplo es sencillo; no identifica instrumentos ni problemas automáticamente.'],
 compression:['Compresión por objetivo','Para controlar picos prueba ataque corto; para conservar la pegada, alárgalo. El umbral decide cuándo actuar, el ratio cuánto y la recuperación cuánto tarda en soltar. Una recuperación demasiado larga puede hundir la nota siguiente; una demasiado corta puede modular o distorsionar.'],
 deess:['De-esser','Es compresión selectiva de la banda sibilante. Escucha las consonantes del ejemplo vocal sintético: un ajuste moderado reduce su dureza; demasiado procesamiento quita articulación. En una voz real hay que localizar la banda, no elegirla por sexo o tesitura.'],
 series:['Compresión en serie','Dos etapas consecutivas reparten tareas: la primera controla picos con ataque de 2 ms y ratio 4:1; la segunda nivela con ataque de 35 ms y ratio 2:1. El umbral de la segunda está 6 dB por debajo del valor elegido. El medidor suma máximos por etapa, no una reducción instantánea simultánea.'],
 parallel:['Compresión paralela','Se suma una copia comprimida a la señal original, con ambas alineadas en el tiempo. Mezcla 0 % es original y 100 % es comprimida. Compara también los extremos para escuchar qué aporta cada camino.'],
 limit:['Limitación','Este ejemplo limita picos de muestras con anticipación de 5 ms. Aumenta la entrada para oír cómo se reduce la diferencia entre ataque y cuerpo. El techo se aplica antes de igualar el volumen de escucha. No es un limitador true-peak: dBFS de muestras no equivale a dBTP, y RMS no equivale a LUFS.'],
 masking:['Enmascaramiento','Escucha melodía y acompañamiento por separado y después juntos. Un registro compartido no prueba enmascaramiento. Compara tres decisiones: bajar el acompañamiento, separarlo una octava o reducir su banda de presencia. Los solos conservan su proporción dentro de la mezcla.'],
};
const specs={frequency:['Frecuencia · Hz',20,12000,10,1000],gain:['Ganancia · dB',-18,18,1,6],q:['Q',.3,12,.1,1],slope:['Pendiente · dB/oct',12,48,12,12],threshold:['Umbral · dBFS',-48,-6,1,-22],ratio:['Ratio',1,20,.5,4],attack:['Ataque · ms',.1,100,1,20],release:['Recuperación · ms',10,1000,10,140],mix:['Señal comprimida · %',0,100,5,50],drive:['Entrada · dB',0,24,1,6],ceiling:['Techo de muestras · dBFS',-18,-1,1,-3],balance:['Acompañamiento · dB',-24,6,1,-8]};
const fields={eq:['frequency','gain','q'],filter:['frequency','slope'],dynamic:['frequency','q','threshold','ratio','attack','release'],compression:['threshold','ratio','attack','release'],deess:['frequency','q','threshold','ratio','attack','release'],series:['threshold','release'],parallel:['threshold','ratio','attack','release','mix'],limit:['drive','ceiling','release'],masking:['balance']};
const modules={eq:'EQ: zona y dirección',q:'EQ: ancho de banda',filter:'Filtro: conserva o quita cuerpo',attack:'Compresión: ataque',release:'Compresión: recuperación',deess:'De-esser: intensidad',masking:'Enmascaramiento: balance',limit:'Limitación: transitorios'};
let ctx=null,node=null,buffers=[],playing=-1,start=0,offset=0,token=0,upload=null,round=null,stats={},bags=new Map(),seed=0,labOutput=null;
try{stats=JSON.parse(localStorage.getItem('crescendo-processing-practice-v1')||'{}');if(!stats||Array.isArray(stats)||typeof stats!=='object')stats={};}catch(_){stats={};}
const lab=$('processingLab'),practice=$('processingPractice');
lab.innerHTML=`<div class="proc-head"><h2>Procesamiento y dinámica</h2><p>Escucha, ajusta y compara. Los ejemplos incluidos se sintetizan aquí; puedes cargar tu propia grabación.</p></div>
<div class="proc-controls"><label>Procesamiento<select id="procMode">${Object.entries(lessons).map(([id,v])=>`<option value="${id}">${v[0]}</option>`).join('')}</select></label><label>Material<select id="procSource"><option value="music">Instrumento armónico sintético</option><option value="drums">Percusión sintética</option><option value="voice">Vocal sintético con sibilantes</option><option value="noise">Ruido de referencia</option><option value="upload" disabled>Mi grabación</option></select></label><label class="proc-upload">Cargar audio<input id="procFile" type="file" accept="audio/*"></label></div>
<p id="procFileStatus" class="proc-note" role="status"></p><details open class="proc-theory"><summary id="procTitle"></summary><p id="procGuide"></p></details>
<div id="procParams" class="proc-controls"></div><div id="maskChoices" class="proc-controls" hidden><label>Decisión<select id="maskDecision"><option value="balance">Balance</option><option value="arrangement">Acompañamiento una octava abajo</option><option value="eq">Recortar presencia del acompañamiento</option></select></label><button type="button" data-solo="lead">Escuchar melodía sola</button><button type="button" data-solo="backing">Escuchar acompañamiento solo</button></div>
<div class="proc-transport"><button type="button" data-lab-play="0">▶ A · Original</button><button type="button" data-lab-play="1">▶ B · Procesado</button><button type="button" id="procStop">■ Detener</button><label><input type="checkbox" id="procMatch" checked> Igualar nivel RMS</label><label>Volumen <input id="procVolume" type="range" min="0" max="0.8" step="0.01" value="0.3"></label></div>
<p id="procPlaying" role="status">Listo para escuchar.</p><canvas id="procWave" width="1000" height="130" aria-label="Envolventes de amplitud de original y procesado"></canvas><p id="procMetrics" class="proc-note"></p><p class="proc-note">A/B conserva la posición del fragmento. Igualación RMS aproximada, no medición de sonoridad perceptual. La escala visual es común para A y B.</p>
<details class="proc-theory"><summary>Fuentes y límites de los ejemplos</summary><p><a href="https://online.berklee.edu/takenote/what-is-eq-in-music-10-audio-equalization-tips/" target="_blank" rel="noopener">Berklee Online: EQ</a> · <a href="https://downloads.izotope.com/docs/ozone8/dynamics/index.html" target="_blank" rel="noopener">iZotope: dinámica</a> · <a href="https://www.fabfilter.com/help/pro-ds" target="_blank" rel="noopener">FabFilter: de-esser</a> · <a href="https://tech.ebu.ch/publications/r128" target="_blank" rel="noopener">EBU R128: sonoridad y true peak</a>.</p><p>Para una entrega profesional, mide LUFS y dBTP con herramientas conformes y sigue la especificación del destino. No hay un nivel único para todas las plataformas. Estos procesadores simplificados enseñan diferencias audibles; no sustituyen un procesador ni un medidor de mastering.</p></details>`;
practice.innerHTML=`<h3>Entrenamiento de mezcla y dinámica</h3><p>Compara A y B antes de responder. Puedes repetirlos libremente; los ejemplos son sintéticos y varían entre rondas.</p><div class="proc-controls"><label>Ejercicio<select id="procExercise">${Object.entries(modules).map(([id,title])=>`<option value="${id}">${title}</option>`).join('')}</select></label><label>Dificultad<select id="procDifficulty"><option value="easy">Inicial</option><option value="medium">Intermedia</option><option value="hard">Avanzada</option></select></label><button id="procNew" type="button">Nueva ronda</button></div><p id="procQuestion">Pulsa Nueva ronda para comenzar.</p><div class="proc-transport"><button id="procHearA" type="button" disabled>▶ A · Referencia</button><button id="procHearB" type="button" disabled>▶ B · Comparación</button><button id="procPracticeStop" type="button">■ Detener</button></div><div id="procPracticeSolos" class="proc-transport" hidden><button type="button" data-practice-solo="0">Conocer melodía sola</button><button type="button" data-practice-solo="1">Conocer acompañamiento solo</button></div><p id="procPracticePlaying" role="status"></p><div id="procAnswers" class="proc-answers"></div><p id="procFeedback" role="status"></p><p id="procProgress" class="proc-note"></p>`;
function audioContext(){if(!ctx){ctx=new (window.AudioContext||window.webkitAudioContext)();}return ctx;}
function stop(reset=true){token++;if(node){const old=node;old.onended=()=>{old.disconnect();old.volume.disconnect();};try{old.volume.gain.cancelScheduledValues(ctx.currentTime);old.volume.gain.setValueAtTime(old.volume.gain.value,ctx.currentTime);old.volume.gain.linearRampToValueAtTime(0,ctx.currentTime+.008);old.stop(ctx.currentTime+.009);}catch(_){old.disconnect();old.volume.disconnect();}node=null;}playing=-1;if(reset)offset=0;document.querySelectorAll('[data-lab-play],#procHearA,#procHearB').forEach(b=>b.setAttribute('aria-pressed','false'));$('procPlaying').textContent='Detenido.';$('procPracticePlaying').textContent='Detenido.';}
async function play(index,pack,label){window.dispatchEvent(new CustomEvent('crescendo:audio-owner',{detail:'processing'}));const current=audioContext();
 const nextOffset=node?(offset+current.currentTime-start)%(buffers[0].length/sr):offset;
 stop(false);const request=token;await current.resume();if(request!==token)return;
 buffers=pack;offset=Math.min(nextOffset,pack[index].length/sr-.001);const b=current.createBuffer(1,pack[index].length,sr);b.copyToChannel(pack[index],0);
 const source=current.createBufferSource(),volume=current.createGain();source.buffer=b;source.loop=true;volume.gain.setValueAtTime(0,current.currentTime);volume.gain.linearRampToValueAtTime(+$('procVolume').value,current.currentTime+.008);source.connect(volume).connect(current.destination);source.onended=()=>volume.disconnect();source.start(0,Math.max(0,offset));node=source;node.volume=volume;playing=index;start=current.currentTime;$('procPlaying').textContent=label;$('procPracticePlaying').textContent=label;
 document.querySelectorAll('[data-lab-play],#procHearA,#procHearB').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.labPlay===String(index)&&pack===labOutput?.matched||b.id===`procHear${index?'B':'A'}`&&pack===round?.audio)));return true;
}
function params(){const p={};for(const key of fields[$('procMode').value])p[key]=Number($('proc-'+key).value);if('mix'in p)p.mix/=100;return p;}
function fieldUI(){const mode=$('procMode').value;$('procTitle').textContent=lessons[mode][0];$('procGuide').textContent=lessons[mode][1];$('maskChoices').hidden=mode!=='masking';$('procSource').disabled=mode==='masking';$('procParams').innerHTML=fields[mode].map(key=>{const [label,min,max,step,def]=specs[key];let value=def;if(mode==='deess'&&key==='frequency')value=6500;if(mode==='deess'&&key==='attack')value=1;if(mode==='filter'&&key==='frequency')value=100;return `<label>${label}<input id="proc-${key}" type="number" min="${min}" max="${max}" step="${step}" value="${value}"></label>`;}).join('');renderLab();}
function masking(seed=1,balance=0,decision='balance'){
 const lead=D.synth('music',seed,sr),backing=D.synth('music',seed+3,sr); // deterministic independent melodic parts
 let changed=backing;
 if(decision==='arrangement'){changed=new Float32Array(backing.length);for(let i=0;i<changed.length;i++)changed[i]=backing[Math.floor(i/2)];}
 if(decision==='eq')changed=D.filter(backing,sr,'peaking',1000,.6,-10);
 return {lead,backing,original:D.mix(lead,backing,.65),changed:Float32Array.from(lead,(v,i)=>v*.35+changed[i]*.65*D.amp(decision==='balance'?balance:0))};
}
function renderLab(){stop();const mode=$('procMode').value,p=params();if(mode==='masking')$('proc-balance').disabled=$('maskDecision').value!=='balance';let original,wet;
 if(mode==='masking'){const m=masking(11,p.balance,$('maskDecision').value);original=m.original;wet={audio:m.changed,reduction:0};labOutput={...m};}
 else {original=$('procSource').value==='upload'&&upload?upload:D.synth($('procSource').value,13,sr);wet=D.process(original,sr,mode,p);labOutput={};}
 labOutput.raw=[original,wet.audio];labOutput.matched=D.matchLevels(labOutput.raw,$('procMatch').checked);const a=D.metrics(original),b=D.metrics(wet.audio);
 $('procMetrics').textContent=`Antes de igualar: pico A ${a.peakDb.toFixed(1)} / B ${b.peakDb.toFixed(1)} dBFS · factor de cresta A ${a.crest.toFixed(1)} / B ${b.crest.toFixed(1)} dB · reducción máxima ${wet.reduction.toFixed(1)} dB.`;draw(labOutput.matched);$('procPlaying').textContent='Pulsa A o B para escuchar.';
}
function draw(pair){const c=$('procWave');c.width=Math.max(280,c.clientWidth||1000);const g=c.getContext('2d');g.font='12px sans-serif';g.clearRect(0,0,c.width,c.height);pair.forEach((x,j)=>{g.strokeStyle=j?'#71b6da':'#d4a84f';g.beginPath();for(let col=0;col<c.width;col++){let peak=0;for(let i=Math.floor(col*x.length/c.width);i<Math.floor((col+1)*x.length/c.width);i++)peak=Math.max(peak,Math.abs(x[i]));const y=120-peak*150;if(!col)g.moveTo(col,y);else g.lineTo(col,y);}g.stroke();});g.fillStyle='#d4a84f';g.fillText('A · Original',12,16);g.fillStyle='#71b6da';g.fillText('B · Procesado',120,16);}
$('procMode').addEventListener('change',()=>{if($('procMode').value==='deess')$('procSource').value='voice';if(['compression','series','parallel','limit'].includes($('procMode').value))$('procSource').value='drums';fieldUI();});
$('procParams').addEventListener('change',e=>{const el=e.target;if(!el.matches('input'))return;let v=Number(el.value);if(!el.value||!Number.isFinite(v))v=Number(el.min);v=Math.max(+el.min,Math.min(+el.max,v));if(el.id==='proc-slope')v=Math.round(v/12)*12;el.value=v;renderLab();});
for(const id of ['procSource','procMatch','maskDecision'])$(id).addEventListener('change',renderLab);
$('procVolume').addEventListener('input',()=>{if(node)node.volume.gain.setTargetAtTime(+$('procVolume').value,ctx.currentTime,.02);});
lab.querySelectorAll('[data-lab-play]').forEach(b=>b.addEventListener('click',()=>safePlay(+b.dataset.labPlay,labOutput.matched,b.textContent)));
lab.querySelectorAll('[data-solo]').forEach(b=>b.addEventListener('click',()=>{stop();safePlay(0,[D.gain(labOutput[b.dataset.solo],b.dataset.solo==='lead'?.35:.65)],b.textContent);}));
for(const id of ['procStop','procPracticeStop'])$(id).addEventListener('click',()=>stop());
function safePlay(...args){play(...args).catch(e=>{$('procFeedback').textContent='No se pudo iniciar el audio: '+e.message;stop();});}
$('procFile').addEventListener('change',async()=>{const file=$('procFile').files[0];if(!file)return;stop();if(file.size>30*1024*1024){$('procFileStatus').textContent='Elige un archivo de hasta 30 MB.';return;}$('procFileStatus').textContent='Preparando audio…';try{const decoded=await audioContext().decodeAudioData(await file.arrayBuffer());const offline=new OfflineAudioContext(1,Math.max(1,Math.floor(Math.min(8,decoded.duration)*sr)),sr),source=offline.createBufferSource();source.buffer=decoded;source.connect(offline.destination);source.start();const rendered=await offline.startRendering();upload=rendered.getChannelData(0).slice();$('procSource').querySelector('[value=upload]').disabled=false;$('procSource').value='upload';$('procFileStatus').textContent=`${file.name} · primeros ${Math.min(8,decoded.duration).toFixed(1)} s, convertidos a mono para comparar. No se sube el archivo.`;renderLab();}catch(e){$('procFileStatus').textContent='No se pudo leer este audio. Prueba WAV o MP3.';}});
function progress(){const key=$('procExercise').value+':'+$('procDifficulty').value,s=stats[key]||{total:0,right:0};$('procProgress').textContent=`Este ejercicio y nivel: ${s.right||0} aciertos de ${s.total||0}. Progreso guardado en este navegador. Comparaciones con nivel RMS igualado.`;}
function newRound(){stop();const kind=$('procExercise').value,difficulty=$('procDifficulty').value,key=kind+':'+difficulty,E=window.ProcessingExercises;if(!bags.has(key))bags.set(key,D.shuffledBag(E.options[kind].map((_,i)=>i)));round=E.create(kind,difficulty,bags.get(key)(),++seed+Math.floor(Math.random()*100000));$('procPracticeSolos').hidden=!round.stems;round.heard=new Set();round.answered=false;$('procQuestion').textContent=round.question;$('procFeedback').textContent='Escucha A y B para habilitar las respuestas.';$('procHearA').disabled=false;$('procHearB').disabled=false;$('procAnswers').replaceChildren();round.choices.forEach((label,i)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.disabled=true;b.addEventListener('click',()=>answer(i));$('procAnswers').append(b);});progress();}
function answer(i){if(!round||round.answered||round.heard.size<2)return;round.answered=true;const key=$('procExercise').value+':'+$('procDifficulty').value;let s=stats[key];if(!s||!Number.isFinite(s.total)||!Number.isFinite(s.right))s={total:0,right:0};s.total++;s.right+=Number(i===round.correct);stats[key]=s;try{localStorage.setItem('crescendo-processing-practice-v1',JSON.stringify(stats));}catch(_){}$('procFeedback').textContent=`${i===round.correct?'Correcto.':'Respuesta: '+round.choices[round.correct]+'.'} ${round.why}`;$('procAnswers').querySelectorAll('button').forEach((b,j)=>{b.disabled=true;b.classList.toggle('proc-correct',j===round.correct);});progress();}
for(const [id,index] of [['procHearA',0],['procHearB',1]])$(id).addEventListener('click',async()=>{if(!round)return;const selected=round;try{const started=await play(index,selected.audio,index?'B · Comparación':'A · Referencia');if(!started||round!==selected)return;selected.heard.add(index);if(selected.heard.size===2&&!selected.answered){$('procAnswers').querySelectorAll('button').forEach(b=>b.disabled=false);$('procFeedback').textContent='Elige lo que escuchaste. Puedes repetir A y B.';}}catch(e){$('procFeedback').textContent='No se pudo iniciar el audio: '+e.message;}});
practice.querySelectorAll('[data-practice-solo]').forEach(b=>b.addEventListener('click',()=>{if(round?.stems){stop();safePlay(0,[D.gain(round.stems[+b.dataset.practiceSolo],.5)],b.textContent);}}));
$('procNew').addEventListener('click',newRound);for(const id of ['procExercise','procDifficulty'])$(id).addEventListener('change',newRound);
window.addEventListener('crescendo:view-change',e=>{stop();if(e.detail?.view==='processing'&&labOutput)draw(labOutput.matched);});
window.addEventListener('resize',()=>{if(labOutput&&lab.clientWidth)draw(labOutput.matched);});
practice.parentElement.addEventListener('toggle',()=>{if(!practice.parentElement.open)stop();});
window.addEventListener('crescendo:audio-owner',e=>{if(e.detail!=='processing')stop();});
window.addEventListener('pagehide',()=>stop());document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
fieldUI();progress();
})();
