const assert=require("node:assert/strict");
const fs=require("node:fs");
const vm=require("node:vm");
const app=fs.readFileSync(__dirname+"/app.js","utf8");
const css=fs.readFileSync(__dirname+"/styles.css","utf8");
assert.match(app,/function mountSoundLab/);
assert.match(app,/function mountReadingLab/);
assert.match(app,/function mountRhythmLab/);
assert.match(app,/function mountIntervalLab/);
assert.match(app,/function mountScaleLab/);
assert.match(app,/function mountTonalityLab/);
assert.match(app,/function mountTriadLab/);
assert.match(app,/AudioContext/);
assert.match(app,/QUICK_PRACTICE/);
assert.match(css,/FASE 2 · APRENDIZAJE INTERACTIVO/);
const context={window:{}};context.window=context;vm.createContext(context);
vm.runInContext(fs.readFileSync(__dirname+"/data.js","utf8"),context);
assert.ok(context.TLM_DATA.levels.length>=7);
console.log("Teoría y Lectura Fase 2: 7 laboratorios interactivos OK.");
