const assert=require("node:assert/strict");
const fs=require("node:fs");
const vm=require("node:vm");
const app=fs.readFileSync(__dirname+"/app.js","utf8");
const css=fs.readFileSync(__dirname+"/styles.css","utf8");
const html=fs.readFileSync(__dirname+"/index.html","utf8");
assert.match(app,/function mountSoundLab/);
assert.match(app,/function mountReadingLab/);
assert.match(app,/function mountRhythmLab/);
assert.match(app,/function mountIntervalLab/);
assert.match(app,/function mountScaleLab/);
assert.match(app,/function mountTonalityLab/);
assert.match(app,/function mountTriadLab/);
assert.match(app,/AudioContext/);
assert.match(html,/soundfont-player@0\.12\.0/,'Debe cargar la misma librería SoundFont del Piano Virtual');
assert.match(app,/Soundfont\.instrument\(ctx,"acoustic_grand_piano"/,'Todos los ejemplos deben usar piano acústico');
assert.doesNotMatch(app,/<option value="sine">/,'No deben ofrecerse ondas sintéticas como timbres musicales');
assert.match(app,/AUDIO\.masterBus\.gain\.value=2/,'El piano debe tener ganancia general duplicada');
assert.doesNotMatch(app,/createDynamicsCompressor/,'El piano no debe pasar por el compresor anterior');
assert.match(app,/QUICK_PRACTICE/);
assert.match(app,/step=index-2/,'Las notas bajo el pentagrama deben conservar posiciones distintas');
assert.match(app,/reading-staff[\s\S]*ledger|ledger[\s\S]*reading-staff/,'Las notas extremas requieren líneas adicionales');
assert.match(app,/tlm-clef/,'Los pentagramas teóricos deben incluir clave');
assert.match(app,/function staffReferenceSVG/,'Debe existir un mapa de referencia de notas');
assert.match(app,/<option value="both" selected>Ambas claves<\/option>/,'El mapa debe permitir mostrar ambas claves');
assert.match(app,/data-reference-note/,'Las notas de referencia deben ser audibles e interactivas');
assert.doesNotMatch(app,/data-new-note/,'El mapa introductorio no debe volver a preguntar notas al alumno');
assert.match(app,/data-rhythm-audition/,'La audición de duraciones debe evitar duplicar la tabla de referencia');
assert.doesNotMatch(app,/rhythm-values-complete/,'No debe existir una segunda tabla completa duplicada');
assert.match(fs.readFileSync(__dirname+"/data.js","utf8"),/Tabla completa de figuras y silencios/,'Debe incluir todas las figuras y sus silencios equivalentes');
assert.match(fs.readFileSync(__dirname+"/data.js","utf8"),/Barras, repeticiones y navegación/,'Debe explicar los signos de navegación musical');
assert.match(fs.readFileSync(__dirname+"/data.js","utf8"),/Referencia aproximada de tempo/,'Debe relacionar metrónomo, BPM e indicaciones de tempo');
assert.match(fs.readFileSync(__dirname+"/data.js","utf8"),/Tipos de compás y acentuación/,'Debe comparar compases simples y compuestos');
assert.match(css,/FASE 2 · APRENDIZAJE INTERACTIVO/);
const context={window:{}};context.window=context;vm.createContext(context);
vm.runInContext(fs.readFileSync(__dirname+"/data.js","utf8"),context);
assert.ok(context.TLM_DATA.levels.length>=7);
console.log("Teoría y Lectura Fase 2: 7 laboratorios interactivos OK.");
