const {test}=require('node:test');const assert=require('node:assert/strict');const {response,frequencyFromText}=require('../eq-response.js');
const band=(type,gain=0,q=.707)=>({type,gain,q,frequency:1000,enabled:true});
test('flat and bypassed bands are transparent',()=>{for(const f of [20,1000,20000]){assert.ok(Math.abs(response(band('peaking'),f))<1e-7);assert.equal(response({...band('highpass'),enabled:false},f),0);}});
test('bell centre reaches requested gain and Q narrows its width',()=>{assert.ok(Math.abs(response(band('peaking',6),1000)-6)<1e-7);assert.ok(response(band('peaking',6,8),1500)<response(band('peaking',6,.5),1500));assert.ok(Math.abs(response(band('peaking',-6),1000)+6)<1e-7);});
test('pass filters have -3 dB cutoff and reject correct side',()=>{for(const type of ['highpass','lowpass'])assert.ok(Math.abs(response(band(type),1000)+3.01)<.01);assert.ok(response(band('highpass'),20)<-60);assert.ok(response(band('lowpass'),20000)<-50);});
test('shelves reach gain at the appropriate end; notch rejects centre',()=>{assert.ok(Math.abs(response(band('lowshelf',6),20)-6)<.01);assert.ok(Math.abs(response(band('highshelf',-6),20000)+6)<.01);assert.ok(response(band('notch'),1000)<-70);});
test('frequency zones use logarithmic midpoint and ignore unspecified zones',()=>{assert.equal(frequencyFromText('500 Hz'),500);assert.ok(Math.abs(frequencyFromText('1.5–3 kHz')-Math.sqrt(1500*3000))<.01);assert.equal(frequencyFromText('Graves no musicales'),null);});

test('instrument example combines every numeric cut and boost without dropping bands',()=>{const {instrumentExample}=require('../eq-response.js');const result=instrumentExample({cuts:[{f:'80 Hz',r:'retumbo'},{f:'Graves no musicales',r:'sin frecuencia'}],boosts:Array.from({length:8},(_,i)=>({f:(i+1)+' kHz',r:'definición'}))});assert.equal(result.bands.length,9);assert.equal(result.bands[0].gain,-3);assert.ok(result.bands.slice(1).every(b=>b.gain===3&&b.enabled));assert.equal(result.unspecified.length,1);});

test('pass slopes keep cutoff at -3 dB and steepen by the selected dB per octave',()=>{for(const type of ['highpass','lowpass'])for(const slope of [6,12,24,36,48]){const b={...band(type),slope};assert.ok(Math.abs(response(b,1000)+3.0103)<.001);const near=type==='highpass'?100:10000,far=type==='highpass'?50:20000;const loss=response(b,near)-response(b,far);if(type==='highpass')assert.ok(Math.abs(loss-20*Math.log10(2)*slope/6)<.05);else assert.ok(loss>slope);assert.equal(response({...b,q:8},1000),response(b,1000));}});
test('pass slope response is finite across all graph frequencies and has no gain peak',()=>{for(const type of ['highpass','lowpass'])for(const slope of [6,12,24,36,48])for(const frequency of [20,1000,20000])for(const f of [20,50,1000,20000]){const v=response({...band(type),slope,frequency},f);assert.ok(Number.isFinite(v));assert.ok(v<=0);}});
