    // ======================================================================
    // METRÓNOMO / PRÁCTICA SINCRONIZADA
    // ======================================================================
    const metroToggle=$('metroToggle'),metroDown=$('metroDown'),metroUp=$('metroUp'),metroTap=$('metroTap'),metroBpmValue=$('metroBpmValue'),metroMeter=$('metroMeter'),metroPulse=$('metroPulse'),metroPlacement=$('metroPlacement'),metroBeat=$('metroBeat');
    let metroRunning=false,metroTimer=null,metroNextTime=0,metroBeatIndex=0,metroStartTime=0,metroTapTimes=[];
    function getMeterTiming(bpm=+metroBpmValue.textContent||80){
      const [num,den]=metroMeter.value.split('/').map(Number); const barQ=num*(4/den);
      const p=metroPulse.value; let pulseQ=p==='quarter'?1:p==='eighth'?.5:p==='dottedQuarter'?1.5:(num===6&&den===8?1.5:1);
      let pulses=barQ/pulseQ; if(!Number.isInteger(Math.round(pulses))||Math.abs(pulses-Math.round(pulses))>.01||pulses<1){pulseQ=(num===6&&den===8)?1.5:1;pulses=barQ/pulseQ}
      return {pulses:Math.max(1,Math.round(pulses)),secondsPerPulse:60/Math.max(15,Math.min(300,bpm))};
    }
    function metroClick(time,accent=false){const c=ensureCtx(),o=c.createOscillator(),g=c.createGain();o.frequency.value=accent?1450:980;g.gain.setValueAtTime(.0001,time);g.gain.exponentialRampToValueAtTime(accent?.18:.11,time+.003);g.gain.exponentialRampToValueAtTime(.0001,time+.045);o.connect(g);g.connect(masterBus);o.start(time);o.stop(time+.055)}
    function showMetroBeat(beat){metroBeat.textContent=beat?String(beat):'—';metroBeat.classList.toggle('is-downbeat',beat===1);metroBeat.setAttribute('aria-label',beat?'Tiempo '+beat:'Metrónomo detenido')}
    function metroSchedule(){if(!metroRunning)return;const c=ensureCtx(),timing=getMeterTiming(),beats=timing.pulses,mode=metroPlacement?.value||'all',division=window.CrescendoRhythm?.PLACEMENTS[mode]?.division||1,seconds=timing.secondsPerPulse/division;while(metroNextTime<c.currentTime+.12){const frame=window.CrescendoRhythm?.placementFrame(mode,metroBeatIndex,beats)||{audible:true,accent:metroBeatIndex%beats===0,beat:metroBeatIndex%beats};if(frame.audible)metroClick(metroNextTime,frame.accent);const shown=frame.beat+1;setTimeout(()=>{if(metroRunning)showMetroBeat(shown)},Math.max(0,(metroNextTime-c.currentTime)*1000));metroBeatIndex++;metroNextTime+=seconds}metroTimer=setTimeout(metroSchedule,25)}
    function startMetro(){if(metroRunning)return;const c=ensureCtx();metroRunning=true;metroBeatIndex=0;metroNextTime=metroStartTime=c.currentTime+.06;metroToggle.textContent='■';metroToggle.classList.add('active');metroToggle.setAttribute('aria-pressed','true');metroToggle.setAttribute('aria-label','Detener metrónomo');metroSchedule()}
    function stopMetro(){metroRunning=false;if(metroTimer)clearTimeout(metroTimer);metroTimer=null;metroToggle.textContent='▶';metroToggle.classList.remove('active');metroToggle.setAttribute('aria-pressed','false');metroToggle.setAttribute('aria-label','Iniciar metrónomo');showMetroBeat(0);if($('metroTiming'))$('metroTiming').textContent=''}
    function evaluateMetroAttack(){if(!metroRunning||!metroStartTime)return;const c=ensureCtx(),pulse=getMeterTiming().secondsPerPulse,elapsed=c.currentTime-metroStartTime,nearest=Math.round(elapsed/pulse),ms=Math.round((elapsed-nearest*pulse)*1000),abs=Math.abs(ms),out=$('metroTiming');if(out){out.textContent=abs<=35?'Centro':ms<0?`${abs} ms antes`:`${abs} ms después`;out.dataset.grade=abs<=35?'center':abs<=80?'near':'far'}return ms}
    function setMetroBpm(v){metroBpmValue.textContent=String(Math.max(15,Math.min(300,Math.round(v))));saveSettings()}
    metroToggle.addEventListener('click',()=>metroRunning?stopMetro():startMetro()); metroDown.addEventListener('click',()=>setMetroBpm(+metroBpmValue.textContent-1)); metroUp.addEventListener('click',()=>setMetroBpm(+metroBpmValue.textContent+1));
    metroTap.addEventListener('click',()=>{const now=performance.now();metroTapTimes=metroTapTimes.filter(t=>now-t<2500);metroTapTimes.push(now);if(metroTapTimes.length>=2){const ds=metroTapTimes.slice(1).map((t,i)=>t-metroTapTimes[i]);setMetroBpm(60000/(ds.reduce((a,b)=>a+b,0)/ds.length))}});
    ;[metroMeter,metroPulse,metroPlacement].filter(Boolean).forEach(e=>e.addEventListener('change',()=>{metroBeatIndex=0;saveSettings()}));
