// ---------- METRÓNOMO ----------
const metroToggle=document.getElementById('metroToggle'), metroBpm=document.getElementById('metroBpm'), metroMeter=document.getElementById('metroMeter'), metroPulse=document.getElementById('metroPulse'), metroBeat=document.getElementById('metroBeat');
let metroRunning=false, metroTimer=null, metroNextTime=0, metroBeatIndex=0, tapTimes=[];
function metroClick(time,accent){const ctx=ensureCtx(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=accent?1500:950;g.gain.setValueAtTime(.0001,time);g.gain.exponentialRampToValueAtTime(accent?.18:.11,time+.002);g.gain.exponentialRampToValueAtTime(.0001,time+.055);o.connect(g).connect(masterBus);o.start(time);o.stop(time+.065)}
function metroSchedule(){if(!metroRunning)return;const ctx=ensureCtx(),timing=getMeterTiming(+metroBpm.value||80),spb=timing.secondsPerPulse,beats=timing.pulses;while(metroNextTime<ctx.currentTime+.12){const idx=metroBeatIndex%beats;metroClick(metroNextTime,idx===0);const shown=idx+1;setTimeout(()=>{if(metroRunning)metroBeat.textContent=shown},Math.max(0,(metroNextTime-ctx.currentTime)*1000));metroBeatIndex++;metroNextTime+=spb}metroTimer=setTimeout(metroSchedule,25)}
function setMetro(on){metroRunning=on;metroToggle.classList.toggle('active',on);metroToggle.setAttribute('aria-pressed',String(on));metroToggle.textContent=on?'■':'▶';clearTimeout(metroTimer);if(on){const ctx=ensureCtx();metroBeatIndex=0;metroNextTime=ctx.currentTime+.05;metroSchedule()}else metroBeat.textContent='1';saveSettings()}
metroToggle.addEventListener('click',()=>setMetro(!metroRunning));
function changeBpm(d){metroBpm.value=Math.max(30,Math.min(300,(+metroBpm.value||80)+d));saveSettings()}
document.getElementById('metroDown').addEventListener('click',()=>changeBpm(-1));document.getElementById('metroUp').addEventListener('click',()=>changeBpm(1));
metroBpm.addEventListener('change',()=>{changeBpm(0)});[metroMeter,metroPulse].forEach(el=>el.addEventListener('change',()=>{metroBeatIndex=0;if(metroRunning)setMetro(true);saveSettings()}));
document.getElementById('metroTap').addEventListener('click',()=>{const now=performance.now();tapTimes=tapTimes.filter(t=>now-t<2500);tapTimes.push(now);if(tapTimes.length>=2){const ds=tapTimes.slice(1).map((t,i)=>t-tapTimes[i]);const avg=ds.reduce((a,b)=>a+b,0)/ds.length;metroBpm.value=Math.max(30,Math.min(300,Math.round(60000/avg)));saveSettings()}});
