(function () {
  "use strict";
  const E = window.CrescendoImprovisationEngine;
  const P = window.CrescendoPractice;
  const mount = document.getElementById("improvisationMount");
  if (!E || !P || !mount) return;

  const units = [
    { title: "Práctica deliberada", objective: "Convierte una intención musical concreta en una sesión breve, medible y cantada.", concept: "Una sesión útil no consiste en tocar mucho material sin dirección. Elige una sola habilidad, trabaja despacio, escucha el resultado y registra qué cambió. Los bloques de quince minutos son una estructura práctica, no una regla biológica.", tips: [["Foco", "Una dificultad por bloque."], ["Voz", "Canta antes o mientras tocas."], ["Registro", "Anota tempo y hallazgo."]], lab: "plan" },
    { title: "Mapa de la escala", objective: "Deja de recorrer la escala solamente de abajo hacia arriba.", concept: "La escala mayor es materia prima, no una respuesta universal para cualquier acorde. Aprende su sonido desde una tonalidad concreta y reorganiza sus grados para evitar que cada línea parezca un ejercicio mecánico.", tips: [["Dirección", "Alterna ascenso y descenso."], ["Registro", "Comienza desde distintos grados."], ["Armonía", "Comprueba siempre el acorde."]], lab: "scale" },
    { title: "Curso de escala mayor", objective: "Convierte una escala conocida en vocabulario utilizable en las doce tonalidades.", concept: "La fluidez no termina al memorizar siete notas. Reorganiza la escala en terceras, tríadas, tétradas, pivotes y pentatónicas; después desplaza células de tres notas sobre 4/4 sin perder el pulso. Practica una tonalidad hasta poder cantar el patrón y luego transpón por el círculo de cuartas.", tips: [["Estructura", "Escala, terceras, tríadas y tétradas."], ["Lenguaje", "Aproxima y pivota hacia notas objetivo."], ["Tiempo", "Agrupa 3 sobre 4 sin mover el pulso."]], lab: "majorCourse" },
    { title: "Intervalos y arpegios", objective: "Construye movilidad interna con saltos, tétradas y permutaciones.", concept: "Los saltos diatónicos y los arpegios revelan la estructura armónica contenida en la escala. Practícalos con conducción suave y no como figuras aisladas: cada nota debe conducir a la siguiente.", tips: [["Terceras", "Conectan voces vecinas."], ["Séptimas", "Definen el color del acorde."], ["Permutación", "Cambia el orden, no el material."]], lab: "scaleAdvanced" },
    { title: "Motivo y desarrollo", objective: "Crea continuidad mediante repetición, secuencia y desplazamiento.", concept: "Una idea corta puede sostener un discurso completo si cambia de altura, dirección, final o ritmo. La repetición deliberada permite que el oyente reconozca la idea; la variación evita que se vuelva predecible.", tips: [["Identidad", "Conserva el contorno."], ["Secuencia", "Desplaza el motivo por grados."], ["Contraste", "Modifica solo un parámetro."]], lab: "motive" },
    { title: "Notas objetivo", objective: "Escucha la llegada a terceras y séptimas dentro de una progresión.", concept: "Una línea adquiere dirección cuando resuelve en una nota estructural del acorde. Primero localiza las notas del arpegio; después conecta los acordes con el movimiento más corto posible.", tips: [["Llegada", "Apunta a un tiempo fuerte."], ["Guías", "Prioriza tercera y séptima."], ["Conexión", "Busca semitonos y tonos."]], lab: "targets" },
    { title: "Aproximaciones", objective: "Rodea una nota objetivo sin perder la referencia armónica.", concept: "Una aproximación cromática funciona por su resolución. La nota externa no sustituye el acorde: crea tensión breve y llega con claridad al objetivo, desde abajo, desde arriba o mediante un cierre envolvente.", tips: [["Abajo", "Semitono inferior al objetivo."], ["Arriba", "Semitono superior al objetivo."], ["Envolvente", "Dos lados, una resolución."]], lab: "approach" },
    { title: "Escalas con gravedad", objective: "Conecta escalas a través de los cambios y aterriza en notas estructurales.", concept: "Una escala adquiere dirección cuando deja de ser una serie mecánica y conduce hacia una nota del acorde siguiente. Compara ii–V–I mayor, iiø–V7♭9–i menor y sustitución tritonal; toca las notas objetivo en tiempos fuertes y escucha cómo cambia la sensación de llegada.", tips: [["Dirección", "Asciende o desciende según el registro."], ["Objetivo", "Prioriza fundamental, tercera o séptima."], ["Contexto", "La escala depende de la función del acorde."]], lab: "gravity" },
    { title: "Time-feel y vocabulario rítmico", objective: "Haz que una sola altura produzca frases con dirección y respiración.", concept: "El ritmo puede estudiarse separado de la altura. Practica síncopas, silencios, tresillos y duraciones mixtas con palmas o una sola nota; luego transfiere exactamente ese contorno a una línea melódica.", tips: [["Silencio", "También articula la frase."], ["Acento", "No todo énfasis cae en el pulso."], ["Transferencia", "Conserva el ritmo al cambiar notas."]], lab: "rhythm" },
    { title: "Pulso interno y desplazamiento", objective: "Mantén el tempo cuando el clic se vuelve escaso o aparece en lugares inesperados.", concept: "El metrónomo no debe cargar con todo el pulso. Recorre el árbol rítmico, desplaza células por el compás y reduce gradualmente la información del clic. Empieza palmando, continúa con una sola nota y termina aplicándolo a una progresión.", tips: [["Ancla", "Siente el pulso antes de tocar."], ["Subdivisión", "Piensa rápido para tocar lento."], ["Registro", "Grábate y detecta si aceleras o retrasas."]], lab: "locking" },
    { title: "Escucha con propósito", objective: "Analiza una interpretación por capas en lugar de intentar oírlo todo a la vez.", concept: "Repite el mismo fragmento y dedica cada escucha a una sola pregunta. Primero reconoce forma y bajo; después melodía y armonía; por último síncopa, registro y relación entre los instrumentos. Registra evidencias concretas, no impresiones generales.", tips: [["Una capa", "Cambia el foco en cada repetición."], ["Evidencia", "Anota el momento exacto que escuchaste."], ["Relación", "Observa cómo una parte responde a otra."]], lab: "listening" },
    { title: "Construcción de un chorus", objective: "Integra material, objetivos, cromatismo y ritmo en una forma completa.", concept: "La integración no significa usar todos los recursos a la vez. Diseña un arco: establece una idea, desarróllala, aumenta la tensión y deja una resolución reconocible. Graba una toma y evalúa decisiones concretas.", tips: [["Inicio", "Presenta una idea sencilla."], ["Desarrollo", "Aumenta densidad gradualmente."], ["Cierre", "Resuelve y deja espacio."]], lab: "integration" }
  ];
  const rootOptions = Object.keys(E.ROOTS).map(r => `<option>${r}</option>`).join("");
  let index = Number(localStorage.getItem("aj-improv-current") || 0);
  let completed = JSON.parse(localStorage.getItem("aj-improv-completed") || "[]");
  let voices=[],audioToken=0,loading=null;
  function stopPlayback(){audioToken++;voices.forEach(v=>{try{v.stop();}catch{}});voices=[];}
  let player = null, audioContext = null, timer = null, remaining = 15 * 60;
  const esc = value => String(value).replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));

  function save() { localStorage.setItem("aj-improv-current", index); localStorage.setItem("aj-improv-completed", JSON.stringify(completed)); }
  function score(events, labels) { return P.sequence(events, { meter: "4/4", labels: !!labels }); }
  async function play(events, bpm, placement="all") {
    stopPlayback();const token=audioToken;
    audioContext ||= new (window.AudioContext || window.webkitAudioContext)();
    await audioContext.resume();
    loading ||= window.Soundfont.instrument(audioContext, "acoustic_grand_piano", { soundfont: "MusyngKite" });
    player = await loading;if(token!==audioToken)return;
    const beat = 60 / bpm; let when = audioContext.currentTime + .08;
    const total=events.reduce((sum,event)=>sum+Number(event.beats||0),0),R=window.CrescendoRhythm,spec=R?.PLACEMENTS[placement],division=spec?.division||1;
    if(R){for(let step=0;step<Math.ceil(total*division);step++){const frame=R.placementFrame(placement,step,4);if(!frame.audible)continue;const t=when+step*beat/division,o=audioContext.createOscillator(),g=audioContext.createGain();o.frequency.value=frame.accent?1500:930;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(frame.accent?.13:.075,t+.002);g.gain.exponentialRampToValueAtTime(.0001,t+.045);o.connect(g).connect(audioContext.destination);voices.push(o);o.start(t);o.stop(t+.055);}}
    events.forEach((event, i) => {
      let duration = event.beats;
      if (event.tieStart) for (let j=i+1; j<events.length && events[j].tied && events[j].midi===event.midi; j++) { duration += events[j].beats; if (!events[j].tieStart) break; }
      if (event.kind !== "rest" && !event.tied) voices.push(player.play(event.midi, when, { duration: Math.max(.03, duration * beat * .92), gain: .8 }));
      when += event.beats * beat;
    });
  }
  function selector(extra, melodic=true) { return `<div class="improv-controls"><label>Tonalidad<select data-root>${rootOptions}</select></label>${extra}${melodic?`<label>Figura<select data-figure><option value="whole">Redondas</option><option value="half">Blancas</option><option value="quarter">Negras</option><option value="eighth" selected>Corcheas</option><option value="sixteenth">Semicorcheas</option><option value="thirtySecond">Fusas</option><option value="triplet">Tresillos</option><option value="sextuplet">Seisillos</option></select></label>`:''}<label>Tempo<input data-bpm type="number" min="40" max="220" value="80"></label><button class="primary" data-generate>Generar</button><button data-play>▶ Escuchar</button><button data-stop>■ Detener</button></div><div class="improv-score" data-score></div><p class="improv-feedback" data-feedback></p>`; }
  function labMarkup(type) {
    if (type === "plan" || type === "integration" || type === "listening") return `<div class="improv-timer"><span class="improv-clock" data-clock>15:00</span><button class="primary" data-timer>Iniciar bloque</button><button data-reset-timer>Reiniciar</button></div><div class="improv-checks">${(type === "plan" ? ["Definí una habilidad concreta.", "Canté el material antes de tocarlo.", "Trabajé a un tempo controlable.", "Anoté un hallazgo y el siguiente paso."] : type === "listening" ? ["Identifiqué la forma y sus secciones.","Seguí únicamente la línea de bajo.","Canté un fragmento de la melodía.","Reconocí al menos una calidad de acorde.","Localicé una síncopa o anticipación.","Describí cómo interactúan dos instrumentos."] : ["Presenté un motivo reconocible.", "Llegué a notas guía de los acordes.", "Usé cromatismo con resolución clara.", "Varié el ritmo e incluí silencios.", "Grabé y escuché una toma completa."]).map(x => `<label><input type="checkbox">${x}</label>`).join("")}</div>`;
    const chordControl=`<label data-chord-control>Acorde<select data-chord><option value="all">Todos los grados</option>${E.DIATONIC.map((c,i)=>`<option value="${i}">${c.roman}</option>`).join('')}</select></label>`;
    if (["scale","majorCourse","scaleAdvanced"].includes(type)) {
      const modes=type==='scale'?['stepwise','intervals','jumps','random','permutation']:type==='scaleAdvanced'?['intervals','jumps','triads','sevenths','permutation','pivots']:['stepwise','intervals','triads','sevenths','threeOverFour','approachThirds','approachTriads','approachChords','pivots','pentatonicLinear','pentatonicSkip','pentatonicChords','pentatonicThree'];
      return selector(`<label>Material<select data-mode>${modes.map(m=>`<option value="${m}">${E.MODES[m].name}</option>`).join('')}</select></label><label data-interval-control>Intervalo<select data-interval>${['Unísonos','Segundas','Terceras','Cuartas','Quintas','Sextas','Séptimas','Octavas'].map((v,i)=>`<option value="${i+1}" ${i===2?'selected':''}>${v}</option>`).join('')}</select></label><label data-direction-control>Dirección<select data-direction><option value="both">Variada</option><option value="up">Ascendente</option><option value="down">Descendente</option></select></label>${chordControl}<label data-inversion-control>Inversión<select data-inversion><option value="all">Todas</option><option value="0">Fundamental</option><option value="1">Primera</option><option value="2">Segunda</option><option value="3">Tercera</option></select></label>`);
    }
    if(type==='motive')return selector(`<label>Desarrollo<select data-transform><option value="sequence">Secuencia por grados</option><option value="inverse">Inversión del contorno</option><option value="retrograde">Retrogradación</option></select></label>`);
    if(type==='targets')return selector(`<label>Armonía<select data-progression><option value="diatonic">Los siete acordes diatónicos</option><option value="major251">ii–V–I mayor</option><option value="turnaround">ii–V–I–vi</option></select></label><label>Objetivo<select data-guide><option value="arpeggios">Fundamental, tercera, quinta y séptima</option><option value="guides">Terceras y séptimas</option></select></label>`);
    if (type === "approach") return selector(`<label>Aproximación<select data-mode><option value="below">Desde abajo</option><option value="above">Desde arriba</option><option value="enclosure">Envolvente superior–inferior</option><option value="enclosureReverse">Envolvente inferior–superior</option><option value="double">Doble inferior</option><option value="doubleAbove">Doble superior</option></select></label>${chordControl}`);
    if (type === "gravity") return selector(`<label>Progresión<select data-progression><option value="major251">ii–V–I mayor</option><option value="minor251">iiø–V7♭9–i menor</option><option value="tritone">ii–subV–I</option></select></label><label>Dirección<select data-mode><option value="down">Descendente</option><option value="up">Ascendente</option></select></label>`);
    if (type === "rhythm") return selector(`<label>Patrón<select data-mode><option value="offbeat">Síncopas</option><option value="rests">Silencios</option><option value="triplets">Tresillos</option><option value="mixed">Duraciones mixtas</option></select></label>`,false);
    if (type === "locking") return selector(`<label>Material<select data-mode><option value="tree">Árbol rítmico</option><option value="charleston">Célula larga</option><option value="reverse">Célula invertida</option><option value="redGarland">Anticipaciones</option><option value="funk">Desplazamiento de semicorcheas</option></select></label><label>Desplazar<select data-shift><option value="0">Sin desplazar</option><option value="0.5">Media parte</option><option value="1">Un pulso</option><option value="1.5">Pulso y medio</option></select></label><label>Clic<select data-placement><option value="all">Todos los pulsos</option><option value="oneThree">1 y 3</option><option value="twoFour">2 y 4</option><option value="beatOne">Solo 1</option><option value="beatFour">Solo 4</option><option value="upbeat">Contratiempo</option><option value="tripletEnd">3.er parcial del tresillo</option><option value="randomMute">Silencios aleatorios</option></select></label><a class="improv-piano-link" href="../piano-virtual/index.html">Piano →</a><a class="improv-piano-link" href="../bass-virtual/index.html">Bajo →</a>`,false);
    return selector("");
  }
  function generate(card) {
    stopPlayback();
    const root = card.querySelector("[data-root]")?.value || "C";
    const type = units[index].lab, mode = card.querySelector("[data-mode]")?.value;
    const options={figure:card.querySelector('[data-figure]')?.value||'eighth',interval:card.querySelector('[data-interval]')?.value,direction:card.querySelector('[data-direction]')?.value,chord:card.querySelector('[data-chord]')?.value,inversion:card.querySelector('[data-inversion]')?.value,transform:card.querySelector('[data-transform]')?.value,progression:card.querySelector('[data-progression]')?.value,guide:card.querySelector('[data-guide]')?.value};
    let events = type === "motive" ? E.motive(root,options) : type === "targets" ? E.targets(root,options) : type === "approach" ? E.approaches(root, mode,options) : type === "gravity" ? E.gravity(root,card.querySelector("[data-progression]")?.value,mode,options) : type === "rhythm" ? E.rhythm(root, mode) : type === "locking" ? E.locking(root,mode,card.querySelector("[data-shift]")?.value) : E.scale(root, mode,options);
    card._events = events; card.querySelector("[data-score]").innerHTML = score(events, type === "targets" || type === "approach" || type === "gravity");
    card.querySelector("[data-feedback]").textContent = type === "rhythm" ? `Primero palméalas; después toca exactamente el mismo ritmo. Patrón ${E.rhythmProgress(mode).used} de ${E.rhythmProgress(mode).total} del ciclo, sin repeticiones.` : type === "locking" ? "Palmea primero. Después usa una sola nota y reduce la información del clic sin cambiar el tempo interno." : type === "gravity" ? "Las etiquetas muestran función y llegada. Comprueba que cada llegada señalada pertenezca al acorde objetivo." : "Canta la línea, tócala despacio y transpórtala a otra tonalidad.";
    if(type!=='rhythm'){const cycle=E.materialProgress();if(cycle)card.querySelector('[data-feedback]').textContent+=` Patrón ${cycle.used} de ${cycle.total} del ciclo.`;}
  }
  function wireLab(card) {
    card.querySelector("[data-stop]")?.addEventListener("click",stopPlayback);
    function syncOptions(){
      const mode=card.querySelector('[data-mode]')?.value,arp=['triads','sevenths'].includes(mode);
      for(const [selector,visible] of [['[data-interval-control]',mode==='intervals'],['[data-chord-control]',arp||units[index].lab==='approach'],['[data-inversion-control]',arp],['[data-direction-control]',!['jumps','random','triads','sevenths'].includes(mode)]]){
        const label=card.querySelector(selector);if(label){label.hidden=!visible;label.querySelector('select').disabled=!visible;}
      }
      const inv=card.querySelector('[data-inversion]');if(inv){inv.querySelector('[value="3"]').disabled=mode==='triads';if(mode==='triads'&&inv.value==='3')inv.value='all';}
    }
    card.querySelector('[data-mode]')?.addEventListener('change',syncOptions);syncOptions();
    const generateButton = card.querySelector("[data-generate]");
    if (generateButton) { generateButton.onclick = () => generate(card); card.querySelector("[data-play]").onclick = () => play(card._events || [], Number(card.querySelector("[data-bpm]").value),card.querySelector("[data-placement]")?.value||"all"); generate(card); }
    const timerButton = card.querySelector("[data-timer]");
    if (timerButton) {
      const clock = card.querySelector("[data-clock]");
      const paint = () => { clock.textContent = `${String(Math.floor(remaining / 60)).padStart(2, "0")}:${String(remaining % 60).padStart(2, "0")}`; };
      timerButton.onclick = () => { if (timer) { clearInterval(timer); timer = null; timerButton.textContent = "Continuar"; return; } timerButton.textContent = "Pausar"; timer = setInterval(() => { remaining = Math.max(0, remaining - 1); paint(); if (!remaining) { clearInterval(timer); timer = null; timerButton.textContent = "Bloque completo"; } }, 1000); };
      card.querySelector("[data-reset-timer]").onclick = () => { clearInterval(timer); timer = null; remaining = 15 * 60; timerButton.textContent = "Iniciar bloque"; paint(); };
    }
  }
  function render() {
    stopPlayback();
    clearInterval(timer); timer = null; remaining = 15 * 60;
    const unit = units[index], percent = Math.round(completed.length / units.length * 100);
    mount.innerHTML = `<header class="improv-head"><p class="kicker">Laboratorio de lenguaje</p><h2>Improvisación jazz</h2><p>Ruta práctica de ${units.length} unidades: escucha, canta, visualiza, toca, transforma y registra. Los ejercicios generan material original en todas las tonalidades.</p><div class="improv-progress" aria-label="${percent}% completado"><span style="width:${percent}%"></span></div></header><div class="improv-layout"><nav class="improv-nav" aria-label="Unidades de improvisación">${units.map((u, i) => `<button type="button" data-unit="${i}" class="${i === index ? "active" : ""}"><span class="unit-number">${i + 1}</span><span>${esc(u.title)}</span><small>${completed.includes(i) ? "✓" : ""}</small></button>`).join("")}</nav><article class="improv-card"><p class="kicker">Unidad ${index + 1} de ${units.length}</p><h3>${esc(unit.title)}</h3><p class="improv-objective">${esc(unit.objective)}</p><section class="improv-concept"><h4>Idea central</h4><p>${esc(unit.concept)}</p></section><div class="improv-tips">${unit.tips.map(t => `<div class="improv-tip"><b>${esc(t[0])}</b><span>${esc(t[1])}</span></div>`).join("")}</div><section class="improv-lab"><div class="improv-lab-head"><div><p class="kicker">Práctica interactiva</p><h4>${["plan","integration","listening"].includes(unit.lab) ? "Bloque de trabajo" : "Generador musical"}</h4><p>${unit.lab==="listening"?"Usa una grabación elegida por el profesor o el alumno y completa una capa por escucha.":"Escucha, canta y toca. Cambia la tonalidad para comprobar que aprendiste el recurso y no una digitación."}</p></div></div>${labMarkup(unit.lab)}</section><div class="improv-actions"><button data-prev ${index === 0 ? "disabled" : ""}>← Anterior</button><button data-complete>${completed.includes(index) ? "✓ Unidad completada" : "Marcar como completada"}</button><button data-next ${index === units.length - 1 ? "disabled" : ""}>Siguiente →</button></div></article></div>`;
    mount.querySelectorAll("[data-unit]").forEach(btn => btn.onclick = () => { index = Number(btn.dataset.unit); save(); render(); });
    mount.querySelector("[data-prev]").onclick = () => { index--; save(); render(); };
    mount.querySelector("[data-next]").onclick = () => { index++; save(); render(); };
    mount.querySelector("[data-complete]").onclick = () => { completed = completed.includes(index) ? completed.filter(x => x !== index) : completed.concat(index); save(); render(); };
    wireLab(mount.querySelector(".improv-card"));
  }
  render();
})();
